# Generated by Django 4.2 on 2023-04-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(default='Talaba kiritilmagan', to='app.student'),
        ),
    ]
