# Generated by Django 4.2 on 2023-04-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_group_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='barcodes/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
