# Generated by Django 4.2 on 2023-04-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_student_student_id_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
