# Generated by Django 4.2 on 2023-04-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='app.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='barcode',
            field=models.CharField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
    ]
