# Generated by Django 4.2 on 2023-04-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_group_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='created_at',
            new_name='crea',
        ),
    ]
