# Generated by Django 4.2 on 2023-04-19 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_created_at_group_crea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='crea',
        ),
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='month',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
