# Generated by Django 4.2 on 2023-04-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_group_crea_group_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='month',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
