# Generated by Django 4.2 on 2023-04-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_subscription_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='barcode',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
