# Generated by Django 4.2 on 2023-04-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('admin', 'Administrator'), ('casher', 'Kassir'), ('teacher', "O'qituvchi")], default='', max_length=10),
            preserve_default=False,
        ),
    ]
