# Generated by Django 4.2 on 2023-04-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_profile_is_active_alter_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='F.I.Sh.', max_length=255, null=True),
        ),
    ]
