# Generated by Django 4.2 on 2023-04-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscription',
            name='cost',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
