# Generated by Django 4.2 on 2023-04-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_profile_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
