# Generated by Django 4.2 on 2023-04-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sms_service',
            field=models.BooleanField(default=False),
        ),
    ]
