# Generated by Django 4.2 on 2023-04-24 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_teacherbonus_balance_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('amount', models.CharField(default=0, max_length=255)),
                ('date', models.DateField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('amount', models.CharField(default=0, max_length=255)),
                ('date', models.DateField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.profile')),
            ],
        ),
    ]
