# Generated by Django 4.2 on 2023-04-24 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_teacherfine_teacherdebt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdebt',
            name='amount',
            field=models.IntegerField(default=0, max_length=255, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
