# Generated by Django 4.2 on 2023-04-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_teacherdebt_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherbonus',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teacherdebt',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teacherfine',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
