# Generated by Django 4.2 on 2023-04-26 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='barcode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacherdebt',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
